name: PR size gate
on: [pull_request]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const added = pr.additions || 0;
            const removed = pr.deletions || 0;
            const total = added + removed;

            console.log(`PR size: +${added} -${removed} = ${total} LOC`);

            // Fail if PR is too large (bot enforces 250 LOC max)
            if (total > 250) {
              core.setFailed(`❌ PR too large (${total} LOC). Keep changes under 250 LOC for easy review.`);
            } else {
              console.log(`✅ PR size OK (${total}/250 LOC)`);
            }
